### ISSUE TITLE
detection of QA tests' failure

### ISSUE THREAD

**Issue by edoapra** [conda-forge/nwchem-feedstock#9]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

The script `run_test.sh` does not see to be able to detect the tests failures. 
See `pyqa3` failure in https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=319210&view=logs&jobId=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&j=9a864fd9-6c8f-52ca-79ce-2aa6dca1a1de&t=10fc5aa2-324e-5982-4c88-6b31fcab16b3

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by ltalirz** [comment]
thanks, I guess replacing `set -x` by `set -ex` in the test script might fix this?

we can fix this in https://github.com/conda-forge/nwchem-feedstock/pull/7 if there's anything more to do there, otherwise we can open a separate PR

**Comment by edoapra** [comment]
https://github.com/conda-forge/nwchem-feedstock/pull/7 is not working yet. Can we stop the  running jobs  so that I can analyze the logs?

**Comment by ltalirz** [comment]
I don't think it's easy to stop the jobs - does it prevent you from looking at the logs?
No need to worry about this from the point of view of cpu time.

**Comment by ltalirz** [comment]
I think I see what you mean - you pushed a new change and now I'm also unable to access the logs at the previous commit (`-lrt does not exist on macos`); unfortunately I closed the tab where I had them open.

It's possible that the the new push caused the logs from the previous test run to be removed/become inacessible - to be honest I'm not entirely sure what the rules are on this

**Comment by edoapra** [comment]
Pushed an update

**Comment by ltalirz** [comment]
fixed in https://github.com/conda-forge/nwchem-feedstock/pull/7

**Comment by edoapra** [comment]
I would re-open this one since the `set -e` change did not fix it.
https://dev.azure.com/conda-forge/84710dde-1620-425b-80d0-4cf5baca359d/_apis/build/builds/319427/logs/43
We need to test it again with the following changes
* in `build.sh` `NWCHEM_MODULES=nwdft solvation driver` (this causes the QA test `pyqa3` to fail)
* in `run_test.sh` I am suggesting the following header
```
#!/bin/bash
set -e
```
If this does not work, I am not sure where to look

**Comment by ltalirz** [comment]
Thanks for pointing this out.



> * in `build.sh` `NWCHEM_MODULES=nwdft solvation driver` (this causes the QA test `pyqa3` to fail)

Just to check: this includes `python` or do I need to add this separately?

> * in `run_test.sh` I am suggesting the following header
> 
> ```
> #!/bin/bash
> set -e
> ```
> 
> If this does not work, I am not sure where to look

Looking at https://github.com/nwchemgit/nwchem/blob/master/QA/doafewqmtests.mpi I suspect the problem is that this script will exit with a non-zero exit code if and only if the very last test fails.
Adding `set -e` in that script should fix the issue.

**Comment by ltalirz** [comment]
P.S. I think the `set -e` behavior is not what one wants for a typical test suite though, where one would like to see the results of all tests (not just up to the first test that fails).

I.e. ideally one could add a line to the end of the script that makes sure to return a nonzero exit code unless all tests passed.

**Comment by edoapra** [comment]
> Thanks for pointing this out.
> 
> > * in `build.sh` `NWCHEM_MODULES=nwdft solvation driver` (this causes the QA test `pyqa3` to fail)
> 
> Just to check: this includes `python` or do I need to add this separately?
> 
The  NWChem build corresponding to `NWCHEM_MODULES=nwdft solvation driver` does not include `python`, however the test `pyqa3` is executed and, since the NWChem executable lacks the python modules, it fails
> > * in `run_test.sh` I am suggesting the following header
> > 
> > ```
> > #!/bin/bash
> > set -e
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If this does not work, I am not sure where to look
> 
> Looking at https://github.com/nwchemgit/nwchem/blob/master/QA/doafewqmtests.mpi I suspect the problem is that this script will exit with a non-zero exit code if and only if the very last test fails.
> Adding `set -e` in that script should fix the issue.

Yes, I believe you are on the right track

**Comment by edoapra** [comment]
> P.S. I think the `set -e` behavior is not what one wants for a typical test suite though, where one would like to see the results of all tests (not just up to the first test that fails).
> 
> I.e. ideally one could add a line to the end of the script that makes sure to return a nonzero exit code unless all tests passed.

Good idea. We could have a patch for this ... could you generate it?

**Comment by ltalirz** [comment]
> The NWChem build corresponding to `NWCHEM_MODULES=nwdft solvation driver` does not include `python`, however the test `pyqa3` is executed and, since the NWChem executable lacks the python modules, it fails

Ah sorry, now I get it. But so is the solution to build without python support or should we try to fix the source of the problem (some missing python modules? where/how would they need to be installed?)

In any case, I'm also fine with disabling python support; it will would then reduce the number of builds down to one per platform I guess.


> > I.e. ideally one could add a line to the end of the script that makes sure to return a nonzero exit code unless all tests passed.
> 
> Good idea. We could have a patch for this ... could you generate it?

Hehe, I was hoping you would know the command (grepping some test logs?) ;-)

The minimalist thing to do would be to just modify the `run_tests.sh` to something like
```
./doafewqmtests.mpi 2 | tee tests.log
! grep "NWChem execution failed" tests.log || exit 1
```
Let me know what you prefer

**Comment by edoapra** [comment]
> > The NWChem build corresponding to `NWCHEM_MODULES=nwdft solvation driver` does not include `python`, however the test `pyqa3` is executed and, since the NWChem executable lacks the python modules, it fails
> 
> Ah sorry, now I get it. But so is the solution to build without python support or should we try to fix the source of the problem (some missing python modules? where/how would they need to be installed?)
> 
I guess I have not being clear enough.  
The NWChem binary with `python` in the `NWCHEM_MODULES` list (e.g. `NWCHEM_MODULES=nwdft solvation driver python`  or `NWCHEM_MODULES=all python`) would get a green light on the `pyqa3` test.  
The whole point of 
1. excluding `python` from `NWCHEM_MODULES` and
2. run the `pyqa3` test
  
is to test if the conda recipe is able to detect test failures

**Comment by ltalirz** [comment]
Hehe, ok I think this time I finally did get it ;-) My confusion came from assuming that the test build with the failure you linked above was actually the latest build of the feedstock (and that I overlooked the test failure).

I see now that you just wanted to make sure that a green check mark actually ensures that all tests passed.
Let me make a quick PR.

**Comment by edoapra** [comment]
Yes, the `grep` change you pushed in the last commit seems a good solution to me.
By the way, what does the `!` character do in the last line of the script?

**Comment by ltalirz** [comment]
> By the way, what does the `!` character do in the last line of the script?

It should just negate the truth value of the exit code of the command
